config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get  '/myreports',    to: 'pages#myreports'
  get  '/feedback/:id', to: 'pages#feedback', as: :feedback
  post '/message',      to: 'pages#message'  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets, only: [:create, :new] do
    resources :reports, only: [:create, :new]
  end
  resources :reports, only: [:index, :show, :update, :edit, :destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer">
    <div class="col-md-8 align-center">
      <h2 class="pt-2 mb-0 fyp-foo-txt">Follow us</h2>
      <div class="footer-links pl-0 mb-0">
        <a href="https://www.tiktok.com/@fypetapp" target="_blank">
          <i class="fab fa-tiktok"></i>
        </a>
        <a href="https://www.facebook.com/FYPet-116975966877862" target="_blank">
          <i class="fab fa-facebook"></i>
        </a>
        <a href="https://www.instagram.com/fypetapp/" target="_blank">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="https://twitter.com/fypetapp" target="_blank">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="https://www.youtube.com/channel/UCuOUxkAz7qwiPxawqht-itQ/" target="_blank">
          <i class="fab fa-youtube"></i>
        </a>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light fypet-navbar">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="fypet-text"><i class="fas fa-paw"></i><h2>Find Your Pet</h2></div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto fypet-navbar-nav">
        <li class="nav-item fypet-nav-item">
          <%= link_to "I Found a Pet", new_pet_path, class: "fypet-nav-link" %>
        </li>
        <li class="nav-item fypet-nav-item">
          <%= link_to "Current Reports", reports_path, class: "fypet-nav-link" %>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item fypet-nav-item">
          <%= link_to myreports_path, class: "fypet-nav-link" do %>
            <i class="fas fa-user"></i><span><%= current_user.email %></span>
          <% end %>
        </li>
        <li class="nav-item fypet-nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: "fypet-nav-link" do %>
            <i class="fas fa-sign-out-alt"></i><span>Leave</span>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item fypet-nav-item">
          <%= link_to "My Reports", myreports_path, class: "fypet-nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>