config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get  '/myreports',    to: 'pages#myreports'
  get  '/feedback/:id', to: 'pages#feedback', as: :feedback
  post '/message',      to: 'pages#message'  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets, only: [:create, :new] do
    resources :reports, only: [:create, :new]
  end
  resources :reports, only: [:index, :show, :update, :edit, :destroy]
end

app/views/pages/feedback.html.erb
<div class="container">
  <div class="new-form">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-6 col-md-offset-6">
        <h3>Feedback on <span id="spn-cto">Report #<%= @report.id %></span> about <span id="spn-cto"><%= @report.pet.name %></span></h3>

        <%= form_with(url: "/message", method: "post") do %>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <label for="exampleFormControlInput1">Your name</label>
                <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="John McClane" autofocus=true >
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <label for="exampleFormControlInput1">Your phone number</label>
                <input type="text" class="form-control" id="exampleFormControlInput2" placeholder="55 7811 2345">
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <label for="exampleFormControlTextarea1">Your feedback</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="5"></textarea>
              </div>
            </div>
          </div>
          <%= submit_tag("Send", class: "btn btn-primary btn-wide btn-align-lft") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1561037404-61cd46aa615b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80);">
  <div class="container">
    <h1>Is your pet lost?</h1>
    <p>We can help you find it!</p>
    <%= link_to "Find My Pet", new_pet_path, class: "btn bt-flat btn-primary btn-fypet" %>
  </div>
</div>

<div class="container">
  <div class="text-center">
    <h2><strong>Recently Reunited Pets</strong> <i class="far fa-heart at-home"></i></h2>
  </div>

  <div class="cards">

    <% @iterator = 0 %>

    <% @recent_reunited.each do |report| %>
      <div class="card-pet">
        <%= link_to report_path(report), class: 'card-link' do %>
          <% if report.pet.photo.attached? %>
            <div class="card-pet-img" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= cl_image_path report.pet.photo.key %>')">
            </div>
          <% else %>
            <div class="card-pet-img" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('https://images.unsplash.com/photo-1561037404-61cd46aa615b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80')">
            </div>
          <% end %>

          <div class="card-pet-infos">
            <div>
              <h2><%= report.pet.name %></h2>
              <p class="testimonials"><%= @testimonials[@iterator] %></p>
              <img src="<%= @user_photos[@iterator] %>" class="card-trip-user-home avatar-bordered-home" />
            </div>
          </div>
        <% end %>
      </div>
      <% @iterator += 1 %>
    <% end %>
  </div>
</div>

app/views/pages/myreports.html.erb
<h1 class="my-reports">My Reports</h1>
<% @reports.each do |report| %>
<%= link_to report_path(report), class: 'card-link' do %>
<div class="card-report-show">
  <div class="card-report-basic">
    <div class="card-report-frame">
      <% if report.status == "Missing" %>
        <h2 style="background-color: rgba(184, 4, 4, 0.808)"><i class="far fa-sad-cry"></i>
      <% elsif report.status == "Found" %>
        <h2 style="background-color: rgba(0,128,0,0.9)"><i class="far fa-smile"></i>
      <% else %>
        <h2><i class="far fa-sad-cry"></i>
      <% end %>
        <%= report.status %>
      </h2>

        <% if report.pet.photo.attached? %>
          <!--<%= cl_image_tag report.pet.photo.key, crop: :fill, class: "card-img-show" %> -->
          <div class="card-report-show-photo" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= cl_image_path report.pet.photo.key %>')">
          </div>
        <% else %>
          <div class="card-report-show-photo" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('https://images.unsplash.com/photo-1561037404-61cd46aa615b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80')">
          <!--
          <img class="card-img-show" src="https://images.unsplash.com/photo-1561037404-61cd46aa615b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80" alt="Card image top">
          -->
        <% end %>
        <% end %>

    </div>
    <div class="card-report-description">
      <%= link_to report_path(report), class: 'card-link' do %>
      <h4><%= report.pet.name %></h4><span><%= report.pet.category.capitalize %></span>
    </div>
    <p class="pet-breed"><%= report.pet.breed %></p>
  </div>
  <div class="card-report-details-show">
    <h3>Details</h3>
    <div class="report-fields">
      <table class="table">
        <tbody>
          <tr>
            <td><strong>Size:</strong></td>
            <td><span><%= report.pet.size %></span></td>
          </tr>
          <tr>
            <td><strong>Color:</strong></td>
            <td><span><%= report.pet.color %></span></td>
          </tr>
          <tr>
            <td><strong>Gender:</strong></td>
            <td><span><%= report.pet.gender %></span></td>
          </tr>
          <tr>
            <td><strong>Age:</strong></td>
            <td><span><%= report.pet.age %></span></td>
          </tr>
          <tr>
            <td><strong>Traits:</strong></td>
            <td></td>
          </tr>
          <tr>
            <td colspan="2"><span><%= report.pet.traits %></span></td>
          </tr>
          <tr>
            <td><strong>Date Lost:</strong></td>
            <td><span><%= report.date.strftime('%a %b %d, %Y') %></span></td>
          </tr>
          <% if report.reward_offered %>
            <tr>
              <td><strong>Reward:</strong></td>
              <td><span><%= report.reward_amount %></span></td>
            </tr>
          <% end %>
          <tr>
            <td><strong>Last seen on:</strong></td>
            <td></td>
          </tr>
          <tr>
            <td colspan="2"><span><%= report.address %></span></td>
          </tr>
          <tr>
          </tr>
        </tbody>
      </table>
    </div>
    <% end %>
  </div>
</div>
<% end %>
<%= link_to "Edit My Profile", edit_user_registration_path, class: "btn bt-flat btn-primary btn-fypet-myreport" %>