config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get  '/myreports',    to: 'pages#myreports'
  get  '/feedback/:id', to: 'pages#feedback', as: :feedback
  post '/message',      to: 'pages#message'  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets, only: [:create, :new] do
    resources :reports, only: [:create, :new]
  end
  resources :reports, only: [:index, :show, :update, :edit, :destroy]
end

app/models/report.rb
class Report < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :user, :pet, :status, :address, :date, presence: true

  belongs_to :user
  belongs_to :pet
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_pet, only: [:new, :create]
  before_action :set_report, only: [:edit, :update]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index
    dropdowns_query = Hash.new
    dropdowns_query[:category] = params[:category] if params[:category].present?
    params[:breed] = "" unless params[:category].present?
    
    dropdowns_query[:color] = params[:color] if params[:color].present?
    dropdowns_query[:breed] = params[:breed] if params[:breed].present?
    
    results = policy_scope(Report)

    if params[:query]
      @center = Geocoder.search(params[:query]).first.coordinates
      results_by_loc = results.geocoded.near(@center, 50).order('date DESC')
    else
      results_by_loc = results
    end

    unless dropdowns_query.empty?
      @reports = results_by_loc.joins(:pet).where(pets: dropdowns_query).order('date DESC')
    else
      @reports = results_by_loc
    end
    # unless dropdowns_query.empty?
    #   @reports = results.joins(:pet).where(pets: dropdowns_query).order('date DESC')
    # else
    #   if params[:query]
    #     @center = Geocoder.search(params[:query]).first.coordinates
    #     @reports = results.geocoded.near(@center, 150).order('date DESC')
    #   elsif user_signed_in?
    #     @user_address = current_user.address
    #     unless @user_address.empty?
    #       @center = Geocoder.search(@user_address).first.coordinates
    #       @reports = results.geocoded.near(@center, 50).order('date DESC')
    #     else
    #       @reports = results.geocoded.order('date DESC')
    #     end
    #   else
    #     @reports = results.geocoded.order('date DESC')
    #   end
    # end

    @markers = @reports.map do |report|
      {
        lat: report.latitude,
        lng: report.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { report: report }),
        image_url: helpers.asset_url(report.pet.category.downcase == "dog" ? 'dog_icon.png' : 'cat_icon.png')
      }
    end
  end

  def create
    @report = Report.new(report_strong_params)
    authorize @report
    
    @report.pet = @pet
    @report.user = current_user
    
    if @report.save
      redirect_to reports_path
      flash[:notice] = "Your report has been created 🙏, feedback is on its way 🤞"
    else
      flash[:alert] = "👀 Please fill up all the fields."
      render "reports/new"
    end
  end

  def new
    @report = Report.new
    @report.pet = @pet
    authorize @report
  end
  
  def show
    @report = Report.find(params[:id])
    authorize @report
  end
  
  def edit
  end
  
  def update
    if params[:reunited]
      reunited = params.require(:reunited)
      reunited_date = reunited == "true" ? Date.today : nil
      @report.reunited = reunited
      @report.reunited_date = reunited_date
    else
      @report.update(report_strong_params)
    end

    if @report.save
      redirect_to report_path
      if params[:reunited]
        if @report.reunited
          flash[:notice] = "These are greats news!! 🎊 Congrats!! 🎉"
        else
          flash[:notice] = "😢 So bad to hear that. 🤞 Don't lose hope."
        end
      else
        flash[:notice] = "👍 It's good to keep updated your reports. 🤞 Don't lose hope."
      end
    else
      render "edit"
      flash[:alert] = "🙇‍♂️ We couldn't update the report."
    end
  end

  def destroy
  end

  private

  def report_strong_params
    params.require(:report).permit(:address, :date, :reward_offered, :reward_amount, :status, :pet_id, :user_id)
  end

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end

  def set_report
    report_id = params.require(:id)
    @report = Report.find(report_id)
    authorize @report
  end

  def user_not_authorized
    flash[:alert] = "⛔ You can modify your own reports only."
    redirect_to(report_path)
  end
end

app/views/reports/_info_window.html.erb
<div class="popup-container">
    <h2><%= report.pet.name %></h2>
      <%= cl_image_tag report.pet.photo.key, crop: :fill, class: "card-img-map" %>
      <p><%= report.address %></p>
      <%= link_to "Details", "reports/#{report.id}", class: "btn btn-primary btn-wide" %>
  </div>

app/views/reports/edit.html.erb
<div class="container">
  <div class="new-form">
    <div class="row justify-content-center pt-3">
      <div class="col-12 col-lg-8">
              
      <%= simple_form_for [@report] do |f| %>
        <div class="form-row">
          <div class="col-md-6">

            <div class="card-new-report">
                  <% if @report.pet.photo.attached? %>
                    <div class="card-new-report-show-photo" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= cl_image_path @report.pet.photo.key %>')">
                    </div>
                  <% else %>
                    <div class="card-new-report-show-photo" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('https://images.unsplash.com/photo-1561037404-61cd46aa615b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80')">
                    </div>
                  <% end %>
              <div class="card-new-report-description">
                <h4 class="desc-name"><%= @report.pet.name %></h4> <h4 class="desc-gender"><%= @report.pet.gender %></h4>
                <p class="desc-breed"><%= @report.pet.breed %></p><p class="desc-category"><%= @report.pet.category.capitalize %></p>
              </div>
            </div>

          </div>

          <div class="col-md-6 pl-3">
            <h3>Report info</h3>
            <p>Please give us details about the incident.</p>

            <div class="form-row">
              <div class="form-group col-md-6">
                <%= f.input :status, 
                            autofocus: true,
                            required: true,
                            collection: ['Missing', 'Found'],
                            label: "Kind of report",
                            placeholder: "Choose Missing or Found",
                            hint: "Select one option from the list." %>
              </div>

              <div class="form-group col-md-6">
                <%= f.input :date, as: :date,
                            required: true,
                            html5: true,
                            input_html: { value: Date.today },
                            label: "When did it happen?" %>
              </div>
            </div>

            <div class="form-row">
              <div class="form-group col-md-12">
                <%= f.input :address, as: :text,
                            required: true %>
              </div>
            </div>
            
            <div class="form-row">
              <div class="form-group col">
                <%= f.input :reward_offered, as: :boolean,
                            checked_value: true, unchecked_value: false,
                            boolean_style: :inline %>
              </div>

              <div class="input-group col">
                <%= f.input :reward_amount, as: :string,
                            disabled: true %>
              </div>
            </div>

            <div class="form-row">
              <%= f.submit class: "btn btn-primary"%>
            </div>
          
          </div>
        </div>
      <% end %>
      
      </div>
    </div>
  </div>
</div>

app/views/reports/index.html.erb
<div>
  <div class="row search-index">
    <div class="left-index text-center">
      <%= form_tag reports_path, method: :get, id: "pet_filter" do %>
        <%= select_tag :category,
          options_for_select([ "Dog", "Cat" ],
          params[:category]),
          prompt: "Pet type",
          class: "dropdown dropdown-filter pl-5"
        %>

        <% available_colors = Pet.select(:color).distinct.map { |pet| pet.color } %>
        <%= select_tag :color,
          options_for_select(available_colors,
          params[:color]),
          prompt: "Color",
          class: "dropdown dropdown-filter"
        %>

        <%
          if params[:category]
            available_breeds = Pet.where(category: params[:category]).select(:breed).distinct.map { |pet| pet.breed }
          else
            available_breeds = []
          end
        %>
        <%= select_tag :breed,
          options_for_select(available_breeds,
          params[:breed]),
          prompt: "Breed",
          class: "dropdown dropdown-filter pl-5"
        %>
      <% end %>
    </div>

    <div class="right-index text-center">
      <h2 class="pets-number pl-5"><span style="color: #E6455A"><%= @reports.length %></span> Pets Found</h2>
      <%= form_tag reports_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query, params[:query], class: "form-inline pl-3", placeholder: "Find pet by location"%>
      <%= submit_tag "Search", class: "btn btn-primary search-pets" %>
      <% end %>
    </div>
  </div>

  <div class="cardsmapcontainer">
    <div class="cards-container">
      <div class="row">
        <% @reports.each_with_index do |report,index| %>
          <div class="card-padding col-sm-12 col-lg-6">
            <div class="card">
              <%= link_to report_path(report), class: 'card-link' do %>
                <% if report.pet.photo.attached? %>
                  <div class="card-img-top" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= cl_image_path report.pet.photo.key %>')">
                  </div>
                <% else %>
                  <div class="card-img-top" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('https://images.unsplash.com/photo-1561037404-61cd46aa615b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80')">
                  </div>
                <% end %>
                <div class="card-text">
                  <h2 class="name"><%= report.pet.name %></h2>
                  <h2 class="address"><%= report.address %></h2>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="container map">
      <div id="map"
        style="width: 100%; height: 500px;"
        data-markers="<%= @markers.to_json %>"
        data-center="<%= @center.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/reports/new.html.erb
<div class="container">
  <div class="new-form">
    <div class="row justify-content-center pt-3">
      <div class="col-12 col-lg-8">
              
      <%= simple_form_for [@pet, @report] do |f| %>
        <div class="form-row">
          <div class="col-md-6">

            <div class="card-new-report">
                  <% if @pet.photo.attached? %>
                    <div class="card-new-report-show-photo" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= cl_image_path @pet.photo.key %>')">
                    </div>
                  <% else %>
                    <div class="card-new-report-show-photo" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('https://images.unsplash.com/photo-1561037404-61cd46aa615b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80')">
                    </div>
                  <% end %>
              <div class="card-new-report-description">
                <h4 class="desc-name"><%= @pet.name %></h4> <h4 class="desc-gender"><%= @pet.gender %></h4>
                <p class="desc-breed"><%= @pet.breed %></p><p class="desc-category"><%= @pet.category.capitalize %></p>
              </div>
            </div>

          </div>

          <div class="col-md-6 pl-3">
            <h3>Report info</h3>
            <p>Please give us details about the incident.</p>

            <div class="form-row">
              <div class="form-group col-md-6">
                <%= f.input :status, 
                            autofocus: true,
                            required: true,
                            collection: ['Missing', 'Found'],
                            label: "Kind of report",
                            placeholder: "Choose Missing or Found",
                            hint: "Select one option from the list." %>
              </div>

              <div class="form-group col-md-6">
                <%= f.input :date, as: :date,
                            required: true,
                            html5: true,
                            input_html: { value: Date.today },
                            label: "When did it happen?" %>
              </div>
            </div>

            <div class="form-row">
              <div class="form-group col-md-12">
                <%= f.input :address, as: :text,
                            required: true %>
              </div>
            </div>
            
            <div class="form-row">
              <div class="form-group col">
                <%= f.input :reward_offered, as: :boolean,
                            checked_value: true, unchecked_value: false,
                            boolean_style: :inline %>
              </div>

              <div class="input-group col">
                <%= f.input :reward_amount, as: :string,
                            disabled: true %>
              </div>
            </div>

            <div class="form-row">
              <%= f.submit class: "btn btn-primary"%>
            </div>
          
          </div>
        </div>
      <% end %>
      
      </div>
    </div>
  </div>
</div>

app/views/reports/show.html.erb
<div class="container">
  <div class="new-form show-report pt-2">
    <div class="row justify-content-center">
      <div class="col-sm-12 col-md-10">

        <div class="row">
          <div class="col-md-5">
            <div class="card-pic-show-report">
              <div class="card-show-report">
                <div class="card-report-header text-center">
                  <% if @report.reunited %>
                    <h2 class="reunited"><i class="far fa-smile-beam"></i> Reunited
                  <% else %>
                    <% if @report.status == "Missing" %>
                      <h2 class="missing"><i class="far fa-sad-cry"></i>
                    <% else %>
                      <h2 class="lost"><i class="far fa-sad-tear"></i>
                    <% end %>
                    <%= @report.status %>
                  <% end %>
                    </h2>
                </div>
                <% if @report.pet.photo.attached? %>
                  <div class="card-new-report-show-photo" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= cl_image_path @report.pet.photo.key %>')">
                  </div>
                <% else %>
                  <div class="card-new-report-show-photo" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('https://images.unsplash.com/photo-1561037404-61cd46aa615b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80')">
                  </div>
                <% end %>
                <div class="card-show-report-description">
                  <h4 class="desc-name">
                    <% if @report.pet.name.empty? %>
                      Unknown
                    <% else %>
                      <%= @report.pet.name %>
                    <% end %>
                  </h4>
                  <h4 class="desc-category"><%= @report.pet.category.capitalize %></h4>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-6">
            <div class="row ml-0">
              <h3>Details for Report #<%= @report.id %></h3>
              <!-- Shows or hide the edit icon according to the current user -->
              <% if policy(@report).edit? && !@report.reunited %> 
                <%= link_to edit_report_path(@report) do %>
                  <i class="fas fa-edit"></i>
                <% end %>
              <% end %>
              <!-- Till here is showed according to Pundit -->
            </div>

            <div class="row">
              <div class="col">
                <h5>Breed:</h5>
              </div>
              <div class="col">
                <h6><%= @report.pet.breed %></h6>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <h5>Size:</h5>
              </div>
              <div class="col">
                <h6><%= @report.pet.size %></h6>
              </div>
            </div>
            
            <div class="row">
              <div class="col">
                <h5>Color:</h5>
              </div>
              <div class="col">
                <h6><%= @report.pet.color %></h6>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <h5>Gender:</h5>
              </div>
              <div class="col">
                <h6><%= @report.pet.gender %></h6>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <h5>Age:</h5>
              </div>
              <div class="col">
                <h6><%= @report.pet.age %></h6>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <h5>Traits:</h5>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <% unless @report.pet.traits.empty? %>
                  <h6><%= @report.pet.traits %></h6>
                <% else %>
                  <h6>None.</h6>
                <% end %>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <h5><%= @report.status %> Date:</h5>
              </div>
              <div class="col">
                <h6><%= @report.date.strftime('%a %b %d, %Y') %></h6>
              </div>
            </div>

            <% if @report.reunited_date %>
              <div class="row">
                <div class="col">
                  <h5>Reunited Date:</h5>
                </div>
                <div class="col">
                  <h6><%= @report.reunited_date.strftime('%a %b %d, %Y') %></h6>
                </div>
              </div>
            <% end %>

            <div class="row">
              <div class="col">
                <h5>Reward:</h5>
              </div>
              <div class="col">
                <h6><%= @report.reward_offered ? @report.reward_amount : "None." %></h6>
              </div>
            </div>

            <div class="row">
              <div class="col">
                <h5>Last seen on:</h5>
              </div>
            </div>
            <div class="row">
              <div class="col">
                <h6><%= @report.address %></h6>
              </div>
            </div>

            <div class="row mt-3 ml-0">
            
              <div class="report-actions">
                <% if user_signed_in? %>
                  <!-- Option for unlist -->
                  <%= simple_form_for @report do |f| %>
                    <%= link_to "To Reports", reports_path, class: "btn btn-success btn-wide" %>
                    <% if policy(@report).edit? %>
                      <% if @report.reunited != true %>
                        <%= hidden_field_tag(:reunited, true) %>
                        <%= f.submit "Reunite", class: "btn btn-primary btn-wide", id: "btn-reunite" %>
                      <% else %>
                        <%= hidden_field_tag(:reunited, false) %>
                        <%= f.submit "#{@report.status} again", class: "btn btn-primary btn-wide", id: "btn-reunite" %>
                      <% end %>
                    <% else %>
                      <%= link_to "Feedback", feedback_path(@report),
                          class: "btn btn-success btn-wide", id: "btn-last" unless @report.reunited %> 
                    <% end %>
                  <% end %>
                <% else %>
                  <%= link_to "To Reports", reports_path, class: "btn btn-success btn-wide" %>
                  <%= link_to "Feedback", feedback_path(@report),
                      class: "btn btn-success btn-wide", id: "btn-last" unless @report.reunited %>
                <% end %>
              </div>
              
            </div>
          </div>
        </div>
    
      </div>
    </div>
  </div>
</div>